/* automatically generated by rust-bindgen */

#![allow(
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals
)]
#![cfg(feature = "nightly")]

#[repr(C)]
pub struct PackedVtable__bindgen_vtable {
    _offset_to_top_0: isize,
    _rtti: *const ::std::os::raw::c_void,
    vfns: PackedVtable__bindgen_vfns,
}
#[repr(C)]
pub struct PackedVtable__bindgen_vfns {
    _complete_destructor:
        ::std::option::Option<unsafe extern "C" fn(this: *mut PackedVtable)>,
    _deleting_destructor:
        ::std::option::Option<unsafe extern "C" fn(this: *mut PackedVtable)>,
}
#[repr(C, packed)]
#[derive(Debug)]
pub struct PackedVtable {
    pub vtable_: *const PackedVtable__bindgen_vfns,
}
#[test]
fn bindgen_test_layout_PackedVtable() {
    assert_eq!(
        ::std::mem::size_of::<PackedVtable>(),
        8usize,
        concat!("Size of: ", stringify!(PackedVtable))
    );
    assert_eq!(
        ::std::mem::align_of::<PackedVtable>(),
        1usize,
        concat!("Alignment of ", stringify!(PackedVtable))
    );
}
impl Default for PackedVtable {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
extern "C" {
    #[link_name = "\u{1}_ZN12PackedVtableD1Ev"]
    pub fn PackedVtable_PackedVtable_destructor(this: *mut PackedVtable);
}
